version: '3'
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7333:80"
    restart: always

  php:
    build:
      context: ./public
      dockerfile: Dockerfile
    volumes:
      - ./public:/public
    depends_on:
      - database
    ports:
      - 9000

  database:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3350:3306
    env_file:
      - .env

  phpmyadmin:
    platform: linux/x86_64
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '7373:80'
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=database
